export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const REQUEST_API_DATA_SUCCESS = 'REQUEST_API_DATA_SUCCESS';